gmail_contacts:
  production:
    client_id: 
    client_secret: 
  development:
    client_id: 
    client_secret: 
  test:
    client_id: 
    client_secret: 

yahoo_mail_contacts:
  production:
    consumer_id:
    consumer_secret:  
  development: 
    consumer_id: 
    consumer_secret: 
  test:
    consumer_id: 
    consumer_secret: 
    
number_of_new_points_to_learn:
  production: 7
  development: 2
  test: 2
  
number_of_skills_for_reviewing:
  production: 15
  development: 6
  test: 2
    
system_email: Encake<no-reply@encake.com>

domain: encake.com

push_notification_key:
  production:
    android: 
  development:
    android: 
  test:
    android: 
    
smtp:
  production:
    username: someusername
    password: somepasword

slow_db_query_threshold:
  production: 500
  development: 1000
  test: 5000

slow_request_threshold:
  production: 500
  development: 1000
  test: 5000

admin_email: 

min_opportunity_possibility: 20

max_opportunity_possibility: 80